version: '3.3'
services:
  server:
    image: bluejedi/go-jun
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - APP_DSN=postgres://db/go_restful?sslmode=disable&user=postgres&password=postgres
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    restart: always
    volumes:
      - ./testdata:/testdata
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "go_restful"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
